### PR TITLE
fix: Updated te UI of The chat component and improved the UX

### LINKED ISSUE #39: Feature: Improve the UI of the chat screen
## Feature Request

The UI of the chat screen should be more user friendly with the chat bubble of the user on the right and the chat bubble of the AI on the left
And A better UX when waiting for the AI resposnse
image

### PR DESCRIPTION
**Pull request by DanielAgbeni**
…hat component

## Description
Updated the UI that the AI chat is on the left and the user chat is on the right.

Fixes https://github.com/devhub-ai/devhub/issues/39

## Type of Change
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Manual Testing
## Checklist
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by DanielAgbeni** [comment]
image
image

**Comment by Abhishek-Mallick** [comment]
Hey @DanielAgbeni can you set the width of the component to be 60% and center it
Maybe use something like `className='w-[60%] flex flex-col'` in the div

Also please update the placeholder's make it more relevant to the project

**Comment by DanielAgbeni** [comment]
Noted

**Comment by DanielAgbeni** [comment]
image
image
image

@Abhishek-Mallick 
How about now?

**Comment by Abhishek-Mallick** [comment]
LGTM!!

**Review by Abhishek-Mallick — APPROVED** [review]

**Pull request merged**
