### PR TITLE
feat(landing-page): Make landing page responsive in mobile and tab mode

### PR DESCRIPTION
**Pull request by spartanns**
## Description
Please provide a summary of the changes made in this pull request. Include any relevant motivation and context for the changes.

Fixes # (issue)

## Type of Change
Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Manual Testing / Jest Test's

## Checklist
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Additional Notes
Add any other context or information that may be helpful for the reviewers.

### CODE REVIEW

**Comment by deepraj21** [comment]
Update the last part of the hero section (only half of the globe should be visible in mobile responsive mode)

image

The FAQ in mobile responsive is still at its 100% width

image


I would request you to pull the latest main branch of repository and make the changes as `navbar.tsx` is giving merge conflict.

**Comment by deepraj21** [comment]
Do you really want to close this PR?
It's almost complete.

**Comment by spartanns** [comment]
I closed this one, and made a new one, you can review it.

**Comment by deepraj21** [comment]
done.
merged it.

**Pull request closed without merging**
